apiVersion: apps/v1
kind: Deployment
metadata:
  name: browseterm-server-development
  namespace: ${NAMESPACE}
  labels:
    app: browseterm-server-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browseterm-server-development
  template:
    metadata:
      labels:
        app: browseterm-server-development
    spec:
      containers:
      - name: browseterm-server-development
        image: ${REPO_NAME}/browseterm-server-development:latest
        ports:
        - containerPort: 9999
        env:
        - name: SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: container-maker-development-service-certs
              key: server.key
        - name: SERVER_CRT
          valueFrom:
            secretKeyRef:
              name: container-maker-development-service-certs
              key: server.crt
        - name: CLIENT_KEY
          valueFrom:
            secretKeyRef:
              name: container-maker-development-service-certs
              key: client.key
        - name: CLIENT_CRT
          valueFrom:
            secretKeyRef:
              name: container-maker-development-service-certs
              key: client.crt
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: container-maker-development-service-certs
              key: ca.crt
        volumeMounts:
        - name: app-code
          mountPath: /app
      volumes:
      - name: app-code
        hostPath:
          path: ${HOSTPATH}
          type: DirectoryOrCreate
