CONTAINER_MAKER_HOST: str = "0.0.0.0"
CONTAINER_MAKER_PORT: int = 50051

CONTAINER_MAKER_KEY_FILE: str = "./cert/client.key"
CONTAINER_MAKER_CERT_FILE: str = "./cert/client.crt"
CONTAINER_MAKER_CA_FILE: str = "./cert/ca.crt"

CONTAINER_MAKER_CERT_ENV_VAR: str = "CLIENT_CRT"
CONTAINER_MAKER_KEY_ENV_VAR: str = "CLIENT_KEY"
CONTAINER_MAKER_CA_ENV_VAR: str = "CA_CRT"
