import os

# Container Maker Config
CONTAINER_MAKER_HOST: str = "container-maker-development-service"
CONTAINER_MAKER_PORT: int = 50052

CONTAINER_MAKER_SERVER_KEY_FILE: str = "./cert/server.key"
CONTAINER_MAKER_SERVER_CERT_FILE: str = "./cert/server.crt"
CONTAINER_MAKER_CLIENT_KEY_FILE: str = "./cert/client.key"
CONTAINER_MAKER_CLIENT_CERT_FILE: str = "./cert/client.crt"
CONTAINER_MAKER_CA_FILE: str = "./cert/ca.crt"

CONTAINER_MAKER_SERVER_CERT_ENV_VAR: str = "CONTAINER_MAKER_SERVER_CRT"
CONTAINER_MAKER_SERVER_KEY_ENV_VAR: str = "CONTAINER_MAKER_SERVER_KEY"
CONTAINER_MAKER_CLIENT_CERT_ENV_VAR: str = "CONTAINER_MAKER_CLIENT_CRT"
CONTAINER_MAKER_CLIENT_KEY_ENV_VAR: str = "CONTAINER_MAKER_CLIENT_KEY"
CONTAINER_MAKER_CA_ENV_VAR: str = "CONTAINER_MAKER_CA_CRT"

# Cert Manager Config
CERT_MANAGER_CRON_JOB_NAME: str = os.getenv("CERT_MANAGER_CRON_JOB_NAME")
CERT_MANAGER_CRON_JOB_NAMESPACE: str = os.getenv("CERT_MANAGER_CRON_JOB_NAMESPACE")
